In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv("weatherAUS.csv")
X=dataset.iloc[:,1:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]
['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 ... 16.9 21.8 'No']
 [0.0 0.0 1.0 ... 17.2 24.3 'No']
 [0.0 0.0 1.0 ... 21.0 23.2 'No']
 ...
 [0.0 0.0 0.0 ... 12.5 26.1 'No']
 [0.0 0.0 0.0 ... 15.1 26.0 'No']
 [0.0 0.0 0.0 ... 15.0 20.9 'No']]


In [ ]:
print(X[:,54])

['W' 'WNW' 'WSW' ... 'N' 'SE' nan]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [54,56,57])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 16.9 21.8 'No']
 [0.0 0.0 0.0 ... 17.2 24.3 'No']
 [0.0 0.0 0.0 ... 21.0 23.2 'No']
 ...
 [0.0 0.0 0.0 ... 12.5 26.1 'No']
 [0.0 0.0 0.0 ... 15.1 26.0 'No']
 [0.0 0.0 0.0 ... 15.0 20.9 'No']]


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y= le.fit_transform(Y)
X[:,-1]=le.fit_transform(X[:,-1])
Y=le.fit_transform(Y)



In [ ]:
print(X)
print(Y)

[[0.0 0.0 0.0 ... 16.9 21.8 0]
 [0.0 0.0 0.0 ... 17.2 24.3 0]
 [0.0 0.0 0.0 ... 21.0 23.2 0]
 ...
 [0.0 0.0 0.0 ... 12.5 26.1 0]
 [0.0 0.0 0.0 ... 15.1 26.0 0]
 [0.0 0.0 0.0 ... 15.0 20.9 0]]
[0 0 0 ... 0 0 2]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :-1])
X[:, :-1] = imputer.transform(X[:,:-1] )

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,Y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:

predictions=classifier.predict(X_test)
print(predictions)


[1 0 1 ... 0 0 1]


In [ ]:
from sklearn.metrics import  accuracy_score
accuracy_score(Y_test, predictions)



0.7742678399560017